
import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://aim-foundation-hub.vercel.app';

  const staticPages = [
    '/',
    '/annual-report',
    '/blog',
    '/blog/threading-changes-the-suidhaga-story',
    '/blog/nurturing-a-kinder-tomorrow-the-story-of-milieu',
    '/blog/the-quiet-revolution-in-womens-health',
    '/blog/redefining-classrooms-for-a-digital-tomorrow',
    '/blog/teaching-beyond-boundaries',
    '/blog/empower-english-story',
    '/blog/crafting-futures-the-krishti-story',
    '/blog/surgery-shouldnt-be-a-luxury',
    '/blog/screening-today-for-a-healthier-tomorrow',
    '/blog/planting-hope-growing-futures',
    '/blog/restoring-sight-rekindling-dreams',
    '/carecircle',
    '/career',
    '/cause-marketing-events',
    '/childcare-initiatives',
    '/childfirst',
    '/code-of-conduct',
    '/connect',
    '/cookie-policy',
    '/corporate-social-responsibility',
    '/cureline',
    '/cyclesafe',
    '/detect',
    '/digiempower',
    '/disaster-management',
    '/donation-policy',
    '/eduaccess',
    '/educational-initiatives',
    '/employee-engagement',
    '/empower-english',
    '/films',
    '/gallery',
    '/gender-equality-initiative',
    '/green-roots',
    '/grievance-redressal',
    '/healthcare-initiatives',
    '/ignite-change-initiative',
    '/individual-donation',
    '/innocent-smiles',
    '/inspire-eduLab',
    '/internship',
    '/internship-policy',
    '/join-us',
    '/krishti',
    '/library',
    '/media',
    '/milieu',
    '/newsletter',
    '/oralscan',
    '/organisation',
    '/payroll-giving',
    '/policies',
    '/press-releases',
    '/privacy-policy',
    '/refund-policy',
    '/relief-to-the-underprivileged',
    '/roots-of-change',
    '/safeguarding-policy',
    '/sheconnects',
    '/sighthope',
    '/soulcircle',
    '/suidhaga',
    '/surgireach',
    '/sustainability-initiatives',
    '/team',
    '/tideshield',
    '/transparency-policy',
    '/vidyashakti',
    '/voices',
    '/volunteer-policy',
    '/volunteering',
    '/workshops-events',
  ];

  const sitemapEntries: MetadataRoute.Sitemap = staticPages.map((path) => ({
    url: `${baseUrl}${path}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: path === '/' ? 1 : 0.8,
  }));

  return sitemapEntries;
}
